#!/bin/bash

TITLE="System Information Report For $HOSTNAME"
CURRENT_TIME="$(date "+%x %r %Z")"
TIMESTAMP="Generated $CURRENT_TIME, by $USER"
UPTIME="$(uptime -p)"
KERNEL="$(uname -r)"
CPU="$(grep -m1 'model name' /proc/cpuinfo | cut -d: -f2)"
MEM="$(free -h | awk '/Mem:/ {print $3 " / " $2}')"

{
echo "<!DOCTYPE html>"
echo "<html>"
echo "<head>"
echo "<title>$TITLE</title>"
echo "<style>"
echo "body { font-family: Arial, sans-serif; background:#0f172a; color:#e2e8f0; margin:40px; }"
echo "h1 { color:#38bdf8; }"
echo ".card { background:#1e293b; padding:20px; border-radius:10px; box-shadow:0 0 10px rgba(0,0,0,0.5); max-width:600px; }"
echo ".label { color:#94a3b8; }"
echo "</style>"
echo "</head>"
echo "<body>"
echo "<div class='card'>"
echo "<h1>$TITLE</h1>"
echo "<p class='label'>$TIMESTAMP</p>"
echo "<hr>"
echo "<p><b>Uptime:</b> $UPTIME</p>"
echo "<p><b>Kernel:</b> $KERNEL</p>"
echo "<p><b>CPU:</b> $CPU</p>"
echo "<p><b>Memory Usage:</b> $MEM</p>"
echo "</div>"
echo "</body>"
echo "</html>"
} > index.html
